# Generated by Django 4.2.1 on 2023-06-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('question_text', models.TextField(max_length=500, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
    ]
